/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;


import Controlador.Controlador;
import bbdd.Conexion;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FerTG
 */
public class Ventas_pedidos extends javax.swing.JFrame {
    private static DefaultTableModel modeloTabla;
    private static DefaultTableModel modeloTabla2;
    /**
     * Creates new form Ventas_pedidos
     */
    public Ventas_pedidos() {
        initComponents();
        
        String[] comicsV = {"ID", "Nombre", "Precio", "Vendido"};
        String[] comicsP = {"ID", "Nombre", "Precio", "Pedido"};
        modeloTabla = new DefaultTableModel(null, comicsV);
        modeloTabla2 = new DefaultTableModel(null, comicsP);
        TablaVentas.setModel(modeloTabla);
        TablaPedidos.setModel(modeloTabla2);
        new Controlador().cargarVentas(modeloTabla);
        new Controlador().cargarPedidos(modeloTabla2);
        this.setDefaultCloseOperation(2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaPedidos = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaVentas = new javax.swing.JTable();
        btnImprimirVentas = new javax.swing.JButton();
        javax.swing.JButton Salir = new javax.swing.JButton();
        btnImprimirPedidos = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TablaPedidos);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 47, 519, 448));

        TablaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(TablaVentas);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 47, 496, 448));

        btnImprimirVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escribir.png"))); // NOI18N
        btnImprimirVentas.setToolTipText("");
        btnImprimirVentas.setAutoscrolls(true);
        btnImprimirVentas.setBorder(null);
        btnImprimirVentas.setBorderPainted(false);
        btnImprimirVentas.setContentAreaFilled(false);
        btnImprimirVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnImprimirVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirVentasActionPerformed(evt);
            }
        });
        jPanel1.add(btnImprimirVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, -1, -1));

        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/cerrar-sesion.png"))); // NOI18N
        Salir.setToolTipText("");
        Salir.setBorder(null);
        Salir.setBorderPainted(false);
        Salir.setContentAreaFilled(false);
        Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        jPanel1.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 560, -1, -1));

        btnImprimirPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/escribir.png"))); // NOI18N
        btnImprimirPedidos.setToolTipText("");
        btnImprimirPedidos.setAutoscrolls(true);
        btnImprimirPedidos.setBorder(null);
        btnImprimirPedidos.setBorderPainted(false);
        btnImprimirPedidos.setContentAreaFilled(false);
        btnImprimirPedidos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnImprimirPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirPedidosActionPerformed(evt);
            }
        });
        jPanel1.add(btnImprimirPedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 500, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/borrar.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 530, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/4844928.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, -1, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_SalirActionPerformed

    private void btnImprimirVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirVentasActionPerformed
        new Controlador().crearInforme(TablaVentas);
        
    }//GEN-LAST:event_btnImprimirVentasActionPerformed

    private void btnImprimirPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirPedidosActionPerformed
        new Controlador().crearInforme(TablaVentas);
    }//GEN-LAST:event_btnImprimirPedidosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Asegurar().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaPedidos;
    private javax.swing.JTable TablaVentas;
    private javax.swing.JButton btnImprimirPedidos;
    private javax.swing.JButton btnImprimirVentas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
